[project]
name = "group-publications"
version = "0.1.0"
description = "Pull publications from DBPL and render them in markdown lists."
readme = "README.rst"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "jinja2>=3.1.6",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.41",
]
