name: Run

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

env:
  JOBS: 2
  DEPS: python3-pip python3-flake8

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out
        uses: actions/checkout@v2

      - name: Install prerequisites
        run: pip install -r requirements.txt
          
          
      - name: Set up
        run: |
          cp example_config.py config.py
          mkdir output

      - name: Test
        run: ./cli.py sync
